[package]
name = "rust-gui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
ropey = "1.3.1"
tree-sitter = "0.20.0"

[build-dependencies]
cc="*"